export enum ECrudAction {
  READ = 'READ',
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
}

export enum ECrudFeature {
  AUTH = 'AUTH',
  ROLE = 'ROLE',
  PERMISSIONS = 'PERMISSIONS',
  USER = 'USER',
  PRODUCT = 'PRODUCT',
  DESTINATION = 'DESTINATION',
  SERVICE_CATEGORY = 'SERVICE_CATEGORY',
  PROVIDER = 'PROVIDER',
  CUSTOMER = 'CUSTOMER',
  BILL = 'BILL',
  BILL_INFO = 'BILL_INFO',
  BILL_SERVICE = 'BILL_SERVICE',
  CITY = 'CITY',
  DISTRICT = 'DISTRICT',
  PAYMENT = 'PAYMENT',
  ORDER ='ORDER',
}
